 int A = 2;
 int B = 3;
 int C = 4;
 int D = 5;
 int E = 10;
 int F = 11;
 int G = 12;
 int S1 = 6;
 int S2 = 7;
 void setup() {
  pinMode(A,OUTPUT);
  pinMode(B,OUTPUT);
  pinMode(C,OUTPUT);
  pinMode(D,OUTPUT);
  pinMode(E,OUTPUT);
  pinMode(F,OUTPUT);
  pinMode(G,OUTPUT);
  pinMode(S1,OUTPUT);
  pinMode(S2,OUTPUT);
  // put your setup code here, to run once:
  digitalWrite(A,HIGH);
  digitalWrite(B,HIGH);
  digitalWrite(C,HIGH);
  digitalWrite(D,HIGH);
  digitalWrite(E,HIGH);
  digitalWrite(F,HIGH);
  digitalWrite(G,HIGH);
}

void loop() {
  // put your main code here, to run repeatedly:
digitalWrite(S2,HIGH);
digitalWrite(A,LOW);
digitalWrite(B,LOW);
digitalWrite(C,LOW);
digitalWrite(D,LOW);
digitalWrite(E,LOW);
digitalWrite(F,LOW);
//digitalWrite(G,LOW);
delay(500);
digitalWrite(S2,HIGH);
digitalWrite(A,HIGH);
digitalWrite(B,LOW);
digitalWrite(C,LOW);
digitalWrite(D,HIGH);
digitalWrite(E,HIGH);
digitalWrite(F,HIGH);
digitalWrite(G,HIGH);
delay(500);
//digitalWrite(S2,HIGH);
//digitalWrite(A,LOW);
//digitalWrite(B,LOW);
////digitalWrite(C,LOW);
//digitalWrite(D,LOW);
//digitalWrite(E,LOW);
////digitalWrite(F,LOW);
//digitalWrite(G,LOW);
//delay(500);
//digitalWrite(S2,HIGH);
//digitalWrite(A,LOW);
//digitalWrite(B,LOW);
//digitalWrite(C,LOW);
//digitalWrite(D,LOW);
////digitalWrite(E,LOW);
////digitalWrite(F,LOW);
//digitalWrite(G,LOW);
//delay(500);
//digitalWrite(S2,HIGH);
////digitalWrite(A,LOW);
//digitalWrite(B,LOW);
//digitalWrite(C,LOW);
////digitalWrite(D,LOW);
////digitalWrite(E,LOW);
//digitalWrite(F,LOW);
//digitalWrite(G,LOW);
//delay(500);
//digitalWrite(S2,HIGH);
//digitalWrite(A,LOW);
//digitalWrite(B,LOW);
//digitalWrite(C,LOW);
//digitalWrite(D,LOW);
//digitalWrite(E,LOW);
//digitalWrite(F,LOW);
////digitalWrite(G,LOW);
//delay(500);
//digitalWrite(S2,HIGH);
//digitalWrite(A,LOW);
//digitalWrite(B,LOW);
//digitalWrite(C,LOW);
//digitalWrite(D,LOW);
//digitalWrite(E,LOW);
//digitalWrite(F,LOW);
////digitalWrite(G,LOW);
//delay(500);
//digitalWrite(S2,HIGH);
//digitalWrite(A,LOW);
//digitalWrite(B,LOW);
//digitalWrite(C,LOW);
////digitalWrite(D,LOW);
////digitalWrite(E,LOW);
////digitalWrite(F,LOW);
//digitalWrite(G,LOW);
//delay(500);
//digitalWrite(S2,HIGH);
//digitalWrite(A,LOW);
//digitalWrite(B,LOW);
//digitalWrite(C,LOW);
//digitalWrite(D,LOW);
//digitalWrite(E,LOW);
//digitalWrite(F,LOW);
////digitalWrite(G,LOW);
//delay(500);
//digitalWrite(S2,HIGH);
//digitalWrite(A,LOW);
//digitalWrite(B,LOW);
//digitalWrite(C,LOW);
////digitalWrite(D,LOW);
////digitalWrite(E,LOW);
//digitalWrite(F,LOW);
//digitalWrite(G,LOW);
//delay(500);
}
